/**
 * @jest-environment node
 */

import { DEFAULT_SORTBYARMOR } from "@/app/armor/components/customSortBy/sorting";
import {
    dominated,
    itemStatsToString,
    knapSack,
    setStatsToString,
} from "@/app/armor/script";
import { deepCloneAndMap } from "@/app/util/script";
import Armor from "@/app/util/types/armor";
import ArmorSet from "@/app/util/types/armorSet";

describe("Armor Optimizer Script", () => {
    test("converts item stats to string", () => {
        const item: Armor = {
            id: "1",
            name: "Item 1",
            weight: 10,
            poise: 5,
            defenses: {
                physical: 3,
                strike: 2,
                slash: 1,
                pierce: 1,
                magic: 2,
                fire: 1,
                lightning: 1,
                holy: 1,
            },
            resistances: {
                "death-blight": 10,
                "scarlet-rot": 5,
                poison: 5,
                hemorrhage: 5,
                frostbite: 5,
                sleep: 5,
                madness: 5,
            },
        };

        const result = itemStatsToString(item);

        expect(result).toEqual([
            "10.0",
            "5",
            "7.0 Standard, 3.0 Physical, 2.0 Strike, 1.0 Slash, 1.0 Pierce, ",
            "5.0 Elemental, 2.0 Magic, 1.0 Fire, 1.0 Lightning, 1.0 Holy, ",
            "5 Scarlet Rot, 5 Poison, 5 Hemorrhage, 5 Frostbite, 5 Sleep, 5 Madness, 10 Death",
        ]);
    });

    test("sets stats to string", () => {
        const set: ArmorSet = {
            helmet: {
                id: "1",
                name: "Item 1",
                weight: 10,
                poise: 5,
                defenses: {
                    physical: 3,
                    strike: 2,
                    slash: 1,
                    pierce: 1,
                    magic: 2,
                    fire: 1,
                    lightning: 1,
                    holy: 1,
                },
                resistances: {
                    "death-blight": 10,
                    "scarlet-rot": 5,
                    poison: 5,
                    hemorrhage: 5,
                    frostbite: 5,
                    sleep: 5,
                    madness: 5,
                },
            },
            chestpiece: {
                id: "2",
                name: "Item 2",
                weight: 11,
                poise: 6,
                defenses: {
                    physical: 4,
                    strike: 3,
                    slash: 2,
                    pierce: 2,
                    magic: 3,
                    fire: 2,
                    lightning: 2,
                    holy: 2,
                },
                resistances: {
                    "death-blight": 11,
                    "scarlet-rot": 6,
                    poison: 6,
                    hemorrhage: 6,
                    frostbite: 6,
                    sleep: 6,
                    madness: 6,
                },
            },
            gauntlets: {
                id: "3",
                name: "Item 3",
                weight: 12,
                poise: 7,
                defenses: {
                    physical: 5,
                    strike: 4,
                    slash: 3,
                    pierce: 3,
                    magic: 4,
                    fire: 3,
                    lightning: 3,
                    holy: 3,
                },
                resistances: {
                    "death-blight": 12,
                    "scarlet-rot": 7,
                    poison: 7,
                    hemorrhage: 7,
                    frostbite: 7,
                    sleep: 7,
                    madness: 7,
                },
            },
            leggings: {
                id: "4",
                name: "Item 4",
                weight: 13,
                poise: 8,
                defenses: {
                    physical: 6,
                    strike: 5,
                    slash: 4,
                    pierce: 4,
                    magic: 5,
                    fire: 4,
                    lightning: 4,
                    holy: 4,
                },
                resistances: {
                    "death-blight": 13,
                    "scarlet-rot": 8,
                    poison: 8,
                    hemorrhage: 8,
                    frostbite: 8,
                    sleep: 8,
                    madness: 8,
                },
            },
        };

        const result = setStatsToString(set);

        expect(result).toEqual([
            "46.0",
            "26",
            "52.0 Standard, 18.0 Physical, 14.0 Strike, 10.0 Slash, 10.0 Pierce, ",
            "44.0 Elemental, 14.0 Magic, 10.0 Fire, 10.0 Lightning, 10.0 Holy, ",
            "26 Scarlet Rot, 26 Poison, 26 Hemorrhage, 26 Frostbite, 26 Sleep, 26 Madness, 46 Death",
        ]);
    });

    test("dominated", () => {
        const set: ArmorSet = {
            helmet: {
                id: "1",
                name: "Item 1",
                weight: 10,
                poise: 5,
                defenses: {
                    physical: 3,
                    strike: 2,
                    slash: 1,
                    pierce: 1,
                    magic: 2,
                    fire: 1,
                    lightning: 1,
                    holy: 1,
                },
                resistances: {
                    "death-blight": 10,
                    "scarlet-rot": 5,
                    poison: 5,
                    hemorrhage: 5,
                    frostbite: 5,
                    sleep: 5,
                    madness: 5,
                },
            },
            chestpiece: {
                id: "2",
                name: "Item 2",
                weight: 11,
                poise: 6,
                defenses: {
                    physical: 4,
                    strike: 3,
                    slash: 2,
                    pierce: 2,
                    magic: 3,
                    fire: 2,
                    lightning: 2,
                    holy: 2,
                },
                resistances: {
                    "death-blight": 11,
                    "scarlet-rot": 6,
                    poison: 6,
                    hemorrhage: 6,
                    frostbite: 6,
                    sleep: 6,
                    madness: 6,
                },
            },
            gauntlets: {
                id: "3",
                name: "Item 3",
                weight: 12,
                poise: 7,
                defenses: {
                    physical: 5,
                    strike: 4,
                    slash: 3,
                    pierce: 3,
                    magic: 4,
                    fire: 3,
                    lightning: 3,
                    holy: 3,
                },
                resistances: {
                    "death-blight": 12,
                    "scarlet-rot": 7,
                    poison: 7,
                    hemorrhage: 7,
                    frostbite: 7,
                    sleep: 7,
                    madness: 7,
                },
            },
            leggings: {
                id: "4",
                name: "Item 4",
                weight: 13,
                poise: 8,
                defenses: {
                    physical: 6,
                    strike: 5,
                    slash: 4,
                    pierce: 4,
                    magic: 5,
                    fire: 4,
                    lightning: 4,
                    holy: 4,
                },
                resistances: {
                    "death-blight": 13,
                    "scarlet-rot": 8,
                    poison: 8,
                    hemorrhage: 8,
                    frostbite: 8,
                    sleep: 8,
                    madness: 8,
                },
            },
        };

        const result = dominated(
            [set.helmet!, set.chestpiece!, set.gauntlets!, set.leggings!],
            {
                helmet: undefined,
                chestpiece: undefined,
                gauntlets: undefined,
                leggings: undefined,
            },
            [],
            deepCloneAndMap(DEFAULT_SORTBYARMOR, [{ physical: true }])
        );

        expect(result).toEqual([
            set.helmet!,
            set.chestpiece!,
            set.gauntlets!,
            set.leggings!,
        ]);
    });

    test("dominated with locked items", () => {
        const set: ArmorSet = {
            helmet: {
                id: "1",
                name: "Item 1",
                weight: 10,
                poise: 5,
                defenses: {
                    physical: 3,
                    strike: 2,
                    slash: 1,
                    pierce: 1,
                    magic: 2,
                    fire: 1,
                    lightning: 1,
                    holy: 1,
                },
                resistances: {
                    "death-blight": 10,
                    "scarlet-rot": 5,
                    poison: 5,
                    hemorrhage: 5,
                    frostbite: 5,
                    sleep: 5,
                    madness: 5,
                },
            },
            chestpiece: {
                id: "2",
                name: "Item 2",
                weight: 11,
                poise: 6,
                defenses: {
                    physical: 4,
                    strike: 3,
                    slash: 2,
                    pierce: 2,
                    magic: 3,
                    fire: 2,
                    lightning: 2,
                    holy: 2,
                },
                resistances: {
                    "death-blight": 11,
                    "scarlet-rot": 6,
                    poison: 6,
                    hemorrhage: 6,
                    frostbite: 6,
                    sleep: 6,
                    madness: 6,
                },
            },
            gauntlets: {
                id: "3",
                name: "Item 3",
                weight: 12,
                poise: 7,
                defenses: {
                    physical: 5,
                    strike: 4,
                    slash: 3,
                    pierce: 3,
                    magic: 4,
                    fire: 3,
                    lightning: 3,
                    holy: 3,
                },
                resistances: {
                    "death-blight": 12,
                    "scarlet-rot": 7,
                    poison: 7,
                    hemorrhage: 7,
                    frostbite: 7,
                    sleep: 7,
                    madness: 7,
                },
            },
            leggings: {
                id: "4",
                name: "Item 4",
                weight: 13,
                poise: 8,
                defenses: {
                    physical: 6,
                    strike: 5,
                    slash: 4,
                    pierce: 4,
                    magic: 5,
                    fire: 4,
                    lightning: 4,
                    holy: 4,
                },
                resistances: {
                    "death-blight": 13,
                    "scarlet-rot": 8,
                    poison: 8,
                    hemorrhage: 8,
                    frostbite: 8,
                    sleep: 8,
                    madness: 8,
                },
            },
        };

        const result = dominated(
            [set.helmet!, set.chestpiece!, set.gauntlets!, set.leggings!],
            {
                helmet: set.helmet!,
                chestpiece: undefined,
                gauntlets: undefined,
                leggings: undefined,
            },
            [],
            deepCloneAndMap(DEFAULT_SORTBYARMOR, [{ physical: true }])
        );

        expect(result).toEqual([set.helmet!]);
    });

    test("dominated with ignored items", () => {
        const set: ArmorSet = {
            helmet: {
                id: "1",
                name: "Item 1",
                weight: 10,
                poise: 5,
                defenses: {
                    physical: 3,
                    strike: 2,
                    slash: 1,
                    pierce: 1,
                    magic: 2,
                    fire: 1,
                    lightning: 1,
                    holy: 1,
                },
                resistances: {
                    "death-blight": 10,
                    "scarlet-rot": 5,
                    poison: 5,
                    hemorrhage: 5,
                    frostbite: 5,
                    sleep: 5,
                    madness: 5,
                },
            },
            chestpiece: {
                id: "2",
                name: "Item 2",
                weight: 11,
                poise: 6,
                defenses: {
                    physical: 4,
                    strike: 3,
                    slash: 2,
                    pierce: 2,
                    magic: 3,
                    fire: 2,
                    lightning: 2,
                    holy: 2,
                },
                resistances: {
                    "death-blight": 11,
                    "scarlet-rot": 6,
                    poison: 6,
                    hemorrhage: 6,
                    frostbite: 6,
                    sleep: 6,
                    madness: 6,
                },
            },
            gauntlets: {
                id: "3",
                name: "Item 3",
                weight: 12,
                poise: 7,
                defenses: {
                    physical: 5,
                    strike: 4,
                    slash: 3,
                    pierce: 3,
                    magic: 4,
                    fire: 3,
                    lightning: 3,
                    holy: 3,
                },
                resistances: {
                    "death-blight": 12,
                    "scarlet-rot": 7,
                    poison: 7,
                    hemorrhage: 7,
                    frostbite: 7,
                    sleep: 7,
                    madness: 7,
                },
            },
            leggings: {
                id: "4",
                name: "Item 4",
                weight: 13,
                poise: 8,
                defenses: {
                    physical: 6,
                    strike: 5,
                    slash: 4,
                    pierce: 4,
                    magic: 5,
                    fire: 4,
                    lightning: 4,
                    holy: 4,
                },
                resistances: {
                    "death-blight": 13,
                    "scarlet-rot": 8,
                    poison: 8,
                    hemorrhage: 8,
                    frostbite: 8,
                    sleep: 8,
                    madness: 8,
                },
            },
        };

        const result = dominated(
            [set.helmet!, set.chestpiece!, set.gauntlets!, set.leggings!],
            {
                helmet: undefined,
                chestpiece: undefined,
                gauntlets: undefined,
                leggings: undefined,
            },
            [set.helmet!],
            deepCloneAndMap(DEFAULT_SORTBYARMOR, [{ physical: true }])
        );

        expect(result).toEqual([
            set.chestpiece!,
            set.gauntlets!,
            set.leggings!,
        ]);
    });

    test("knapsack", () => {
        const helmets = [
            {
                id: "alberichs-pointed-hat-altered",
                name: "Alberich's Pointed Hat (Altered)",
                defenses: {
                    physical: 0.9,
                    slash: 0.9,
                    strike: 0.2,
                    pierce: 0.9,
                    magic: 4.4,
                    fire: 3.8,
                    lightning: 4.0,
                    holy: 4.4,
                },
                resistances: {
                    "scarlet-rot": 12,
                    poison: 12,
                    hemorrhage: 7,
                    frostbite: 7,
                    sleep: 23,
                    madness: 23,
                    "death-blight": 24,
                },
                poise: 1,
                weight: 1.0,
            },
            {
                id: "no-helmet",
                name: "No helmet",
                defenses: {
                    physical: 0,
                    strike: 0,
                    slash: 0,
                    pierce: 0,
                    magic: 0,
                    fire: 0,
                    lightning: 0,
                    holy: 0,
                },
                resistances: {
                    poison: 0,
                    "scarlet-rot": 0,
                    hemorrhage: 0,
                    frostbite: 0,
                    sleep: 0,
                    madness: 0,
                    "death-blight": 0,
                },
                poise: 0,
                weight: 0,
            },
            {
                id: "alberichs-pointed-hat",
                name: "Alberich's Pointed Hat",
                defenses: {
                    physical: 1.8,
                    slash: 1.8,
                    strike: 1.4,
                    pierce: 1.8,
                    magic: 4.6,
                    fire: 4.2,
                    lightning: 4.4,
                    holy: 4.6,
                },
                resistances: {
                    "scarlet-rot": 16,
                    poison: 16,
                    hemorrhage: 10,
                    frostbite: 10,
                    sleep: 29,
                    madness: 29,
                    "death-blight": 31,
                },
                poise: 2,
                weight: 1.7,
            },
        ];
        const chestpieces = [
            {
                id: "alberichs-robe",
                name: "Alberich's Robe",
                defenses: {
                    physical: 5.3,
                    slash: 5.3,
                    strike: 4.2,
                    pierce: 5.3,
                    magic: 12.8,
                    fire: 11.9,
                    lightning: 12.4,
                    holy: 12.8,
                },
                resistances: {
                    "scarlet-rot": 38,
                    poison: 38,
                    hemorrhage: 23,
                    frostbite: 23,
                    sleep: 67,
                    madness: 67,
                    "death-blight": 71,
                },
                poise: 7,
                weight: 4.1,
            },
        ];
        const gauntlets = [
            {
                id: "alberichs-bracers",
                name: "Alberich's Bracers",
                defenses: {
                    physical: 1.3,
                    slash: 1.3,
                    strike: 1.0,
                    pierce: 1.3,
                    magic: 3.2,
                    fire: 2.9,
                    lightning: 3.1,
                    holy: 3.2,
                },
                resistances: {
                    "scarlet-rot": 13,
                    poison: 13,
                    hemorrhage: 8,
                    frostbite: 8,
                    sleep: 22,
                    madness: 22,
                    "death-blight": 24,
                },
                poise: 1,
                weight: 1.4,
            },
            {
                id: "no-gauntlets",
                name: "No gauntlets",
                defenses: {
                    physical: 0,
                    strike: 0,
                    slash: 0,
                    pierce: 0,
                    magic: 0,
                    fire: 0,
                    lightning: 0,
                    holy: 0,
                },
                resistances: {
                    poison: 0,
                    "scarlet-rot": 0,
                    hemorrhage: 0,
                    frostbite: 0,
                    sleep: 0,
                    madness: 0,
                    "death-blight": 0,
                },
                poise: 0,
                weight: 0,
            },
            {
                id: "all-knowing-gauntlets",
                name: "All-Knowing Gauntlets",
                defenses: {
                    physical: 3.2,
                    slash: 3.3,
                    strike: 2.9,
                    pierce: 2.9,
                    magic: 3.1,
                    fire: 2.3,
                    lightning: 2.5,
                    holy: 2.1,
                },
                resistances: {
                    "scarlet-rot": 9,
                    poison: 9,
                    hemorrhage: 15,
                    frostbite: 15,
                    sleep: 7,
                    madness: 7,
                    "death-blight": 7,
                },
                poise: 5,
                weight: 3.5,
            },
        ];
        const leggings = [
            {
                id: "no-leggings",
                name: "No leggings",
                defenses: {
                    physical: 0,
                    strike: 0,
                    slash: 0,
                    pierce: 0,
                    magic: 0,
                    fire: 0,
                    lightning: 0,
                    holy: 0,
                },
                resistances: {
                    poison: 0,
                    "scarlet-rot": 0,
                    hemorrhage: 0,
                    frostbite: 0,
                    sleep: 0,
                    madness: 0,
                    "death-blight": 0,
                },
                poise: 0,
                weight: 0,
            },
            {
                id: "all-knowing-greaves",
                name: "All-Knowing Greaves",
                defenses: {
                    physical: 7.4,
                    slash: 7.7,
                    strike: 6.8,
                    pierce: 6.8,
                    magic: 7.1,
                    fire: 5.4,
                    lightning: 5.8,
                    holy: 5.0,
                },
                resistances: {
                    "scarlet-rot": 17,
                    poison: 17,
                    hemorrhage: 29,
                    frostbite: 29,
                    sleep: 13,
                    madness: 13,
                    "death-blight": 13,
                },
                poise: 13,
                weight: 6.6,
            },
            {
                id: "alberichs-trousers",
                name: "Alberich's Trousers",
                defenses: {
                    physical: 3.0,
                    slash: 3.0,
                    strike: 2.3,
                    pierce: 3.0,
                    magic: 7.3,
                    fire: 6.8,
                    lightning: 7.2,
                    holy: 7.3,
                },
                resistances: {
                    "scarlet-rot": 26,
                    poison: 26,
                    hemorrhage: 14,
                    frostbite: 14,
                    sleep: 41,
                    madness: 41,
                    "death-blight": 44,
                },
                poise: 5,
                weight: 2.5,
            },
        ];

        let result = knapSack(
            30,
            helmets,
            chestpieces,
            gauntlets,
            leggings,
            deepCloneAndMap(DEFAULT_SORTBYARMOR, [{ physical: true }])
        );

        expect(result).toEqual([
            {
                chestpiece: {
                    defenses: {
                        fire: 11.9,
                        holy: 12.8,
                        lightning: 12.4,
                        magic: 12.8,
                        physical: 5.3,
                        pierce: 5.3,
                        slash: 5.3,
                        strike: 4.2,
                    },
                    id: "alberichs-robe",
                    name: "Alberich's Robe",
                    poise: 7,
                    resistances: {
                        "death-blight": 71,
                        frostbite: 23,
                        hemorrhage: 23,
                        madness: 67,
                        poison: 38,
                        "scarlet-rot": 38,
                        sleep: 67,
                    },
                    weight: 4.1,
                },
                fitness: 17.700000000000003,
                gauntlets: {
                    defenses: {
                        fire: 2.3,
                        holy: 2.1,
                        lightning: 2.5,
                        magic: 3.1,
                        physical: 3.2,
                        pierce: 2.9,
                        slash: 3.3,
                        strike: 2.9,
                    },
                    id: "all-knowing-gauntlets",
                    name: "All-Knowing Gauntlets",
                    poise: 5,
                    resistances: {
                        "death-blight": 7,
                        frostbite: 15,
                        hemorrhage: 15,
                        madness: 7,
                        poison: 9,
                        "scarlet-rot": 9,
                        sleep: 7,
                    },
                    weight: 3.5,
                },
                helmet: {
                    defenses: {
                        fire: 4.2,
                        holy: 4.6,
                        lightning: 4.4,
                        magic: 4.6,
                        physical: 1.8,
                        pierce: 1.8,
                        slash: 1.8,
                        strike: 1.4,
                    },
                    id: "alberichs-pointed-hat",
                    name: "Alberich's Pointed Hat",
                    poise: 2,
                    resistances: {
                        "death-blight": 31,
                        frostbite: 10,
                        hemorrhage: 10,
                        madness: 29,
                        poison: 16,
                        "scarlet-rot": 16,
                        sleep: 29,
                    },
                    weight: 1.7,
                },
                leggings: {
                    defenses: {
                        fire: 5.4,
                        holy: 5,
                        lightning: 5.8,
                        magic: 7.1,
                        physical: 7.4,
                        pierce: 6.8,
                        slash: 7.7,
                        strike: 6.8,
                    },
                    id: "all-knowing-greaves",
                    name: "All-Knowing Greaves",
                    poise: 13,
                    resistances: {
                        "death-blight": 13,
                        frostbite: 29,
                        hemorrhage: 29,
                        madness: 13,
                        poison: 17,
                        "scarlet-rot": 17,
                        sleep: 13,
                    },
                    weight: 6.6,
                },
                weight: 15.9,
            },
            {
                chestpiece: {
                    defenses: {
                        fire: 11.9,
                        holy: 12.8,
                        lightning: 12.4,
                        magic: 12.8,
                        physical: 5.3,
                        pierce: 5.3,
                        slash: 5.3,
                        strike: 4.2,
                    },
                    id: "alberichs-robe",
                    name: "Alberich's Robe",
                    poise: 7,
                    resistances: {
                        "death-blight": 71,
                        frostbite: 23,
                        hemorrhage: 23,
                        madness: 67,
                        poison: 38,
                        "scarlet-rot": 38,
                        sleep: 67,
                    },
                    weight: 4.1,
                },
                fitness: 16.8,
                gauntlets: {
                    defenses: {
                        fire: 2.3,
                        holy: 2.1,
                        lightning: 2.5,
                        magic: 3.1,
                        physical: 3.2,
                        pierce: 2.9,
                        slash: 3.3,
                        strike: 2.9,
                    },
                    id: "all-knowing-gauntlets",
                    name: "All-Knowing Gauntlets",
                    poise: 5,
                    resistances: {
                        "death-blight": 7,
                        frostbite: 15,
                        hemorrhage: 15,
                        madness: 7,
                        poison: 9,
                        "scarlet-rot": 9,
                        sleep: 7,
                    },
                    weight: 3.5,
                },
                helmet: {
                    defenses: {
                        fire: 3.8,
                        holy: 4.4,
                        lightning: 4,
                        magic: 4.4,
                        physical: 0.9,
                        pierce: 0.9,
                        slash: 0.9,
                        strike: 0.2,
                    },
                    id: "alberichs-pointed-hat-altered",
                    name: "Alberich's Pointed Hat (Altered)",
                    poise: 1,
                    resistances: {
                        "death-blight": 24,
                        frostbite: 7,
                        hemorrhage: 7,
                        madness: 23,
                        poison: 12,
                        "scarlet-rot": 12,
                        sleep: 23,
                    },
                    weight: 1,
                },
                leggings: {
                    defenses: {
                        fire: 5.4,
                        holy: 5,
                        lightning: 5.8,
                        magic: 7.1,
                        physical: 7.4,
                        pierce: 6.8,
                        slash: 7.7,
                        strike: 6.8,
                    },
                    id: "all-knowing-greaves",
                    name: "All-Knowing Greaves",
                    poise: 13,
                    resistances: {
                        "death-blight": 13,
                        frostbite: 29,
                        hemorrhage: 29,
                        madness: 13,
                        poison: 17,
                        "scarlet-rot": 17,
                        sleep: 13,
                    },
                    weight: 6.6,
                },
                weight: 15.2,
            },
            {
                chestpiece: {
                    defenses: {
                        fire: 11.9,
                        holy: 12.8,
                        lightning: 12.4,
                        magic: 12.8,
                        physical: 5.3,
                        pierce: 5.3,
                        slash: 5.3,
                        strike: 4.2,
                    },
                    id: "alberichs-robe",
                    name: "Alberich's Robe",
                    poise: 7,
                    resistances: {
                        "death-blight": 71,
                        frostbite: 23,
                        hemorrhage: 23,
                        madness: 67,
                        poison: 38,
                        "scarlet-rot": 38,
                        sleep: 67,
                    },
                    weight: 4.1,
                },
                fitness: 15.9,
                gauntlets: {
                    defenses: {
                        fire: 2.3,
                        holy: 2.1,
                        lightning: 2.5,
                        magic: 3.1,
                        physical: 3.2,
                        pierce: 2.9,
                        slash: 3.3,
                        strike: 2.9,
                    },
                    id: "all-knowing-gauntlets",
                    name: "All-Knowing Gauntlets",
                    poise: 5,
                    resistances: {
                        "death-blight": 7,
                        frostbite: 15,
                        hemorrhage: 15,
                        madness: 7,
                        poison: 9,
                        "scarlet-rot": 9,
                        sleep: 7,
                    },
                    weight: 3.5,
                },
                helmet: {
                    defenses: {
                        fire: 0,
                        holy: 0,
                        lightning: 0,
                        magic: 0,
                        physical: 0,
                        pierce: 0,
                        slash: 0,
                        strike: 0,
                    },
                    id: "no-helmet",
                    name: "No helmet",
                    poise: 0,
                    resistances: {
                        "death-blight": 0,
                        frostbite: 0,
                        hemorrhage: 0,
                        madness: 0,
                        poison: 0,
                        "scarlet-rot": 0,
                        sleep: 0,
                    },
                    weight: 0,
                },
                leggings: {
                    defenses: {
                        fire: 5.4,
                        holy: 5,
                        lightning: 5.8,
                        magic: 7.1,
                        physical: 7.4,
                        pierce: 6.8,
                        slash: 7.7,
                        strike: 6.8,
                    },
                    id: "all-knowing-greaves",
                    name: "All-Knowing Greaves",
                    poise: 13,
                    resistances: {
                        "death-blight": 13,
                        frostbite: 29,
                        hemorrhage: 29,
                        madness: 13,
                        poison: 17,
                        "scarlet-rot": 17,
                        sleep: 13,
                    },
                    weight: 6.6,
                },
                weight: 14.2,
            },
        ]);
    });
});
